
services:

  nodered:
    container_name: nodered_WMSTATION
    image: nodered/node-red:latest
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
#- node-red-data:/data #mount a docker named volume called `node_red_data` to the container /data directory so any changes made to flows are persisted
      - S:/OneDrive/docker_data/nodered_data:/data #save flow info in local folder instead of inside docker folder
    environment:
      - TZ=Europe/Lisbon
    networks:
      - monitoringNetwork

  grafana:
    container_name: grafana_WMSTATION
    image: grafana/grafana:latest
    ports:
      - 8085:3000
    volumes:
      - grafana_2026_data:/var/lib/grafana
    networks:
      - monitoringNetwork
      


  influxdb:
    container_name: influxdb_WMSTATION
    image: influxdb:latest
    ports:
      - 8087:8086
    volumes:
      - influxdb_data:/var/lib/influxdb3
    networks:
      - monitoringNetwork
      

#Named volumes used/created
volumes:
  grafana_2026_data:
  influxdb_data:


# expose the container's network 
networks:
  monitoringNetwork:
    external: true
    name: monitoringNetwork


    