
services:

  nodered:
    container_name: nodered_WMSTATION
    image: nodered/node-red:latest
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
#- node-red-data:/data #mount a docker named volume called `node_red_data` to the container /data directory so any changes made to flows are persisted
      - S:/OneDrive/docker_data/nodered_data:/data #save flow info in local folder instead of inside docker folder
    environment:
      - TZ=Europe/Lisbon


volumes:
  node-red-data:

